
1. Create a trigger t1 that for every new order entry automatically fills the o_orderdate attribute with the date 2023-12-01. Insert into orders all the orders from December 1995, paying close attention on how the o_orderkey attribute is set. Write a query that returns the number of orders from 2023. Put all the three SQL statements in file test/1.sql. (3 points)

2. Create a trigger t2 that sets a warning Negative balance!!! in the comment attribute of the customer table every time c_acctbal is updated to a negative value from a positive one. Write a SQL statement that sets the balance to -100 for all the customers in AFRICA. Write a query that returns the number of customers with negative balance from EGYPT. Put all the SQL statements in file test/2.sql. (3 points)

3. Create a trigger t3 that resets the comment to Positive balance if the balance goes back positive from negative. Write a SQL statement that sets the balance to 100 for all the customers in MOZAMBIQUE. Write a query that returns the number of customers with negative balance from AFRICA. Put all the SQL statements in file test/3.sql. (3 points)

4. Create triggers that update the attribute o_orderpriority to HIGH every time a new lineitem tuple is added to or deleted from that order. Delete all the line items corresponding to orders from December 1995. Write a query that returns the number of HIGH priority orders in the interval September - December 1995. Put all the SQL statements in file test/4.sql. (3 points)

5. Create a trigger t5 that removes all the tuples from partsupp and lineitem corresponding to a part being deleted. Delete all the parts supplied by suppliers from KENYA or MOROCCO. Write a query that returns the number of parts supplied by every supplier in AFRICA grouped by their country in increasing order. Put all the SQL statements in file test/5.sql. (3 points)